import type { Metadata } from "next";
import "./globals.css";
import { lato } from "./lato";
 
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={lato.variable}>
      <body >{children}</body>
    </html>
  );
}
