import type { Metadata } from "next";
import { baseFont } from "./fonts/baseFont";
import "../app/icons.css";           
import "../app/globals.css";       
 
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={baseFont.variable}>
      <body >{children}</body>
    </html>
  );
}
